services:
  - type: web
    name: sydney-events-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: "5000"
      - key: GOOGLE_CLIENT_ID
        value: "SET_ME"
      - key: FRONTEND_URL
        value: "SET_ME"
      - key: MONGO_URI
        value: "SET_ME"

  - type: web
    name: sydney-events-frontend
    env: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: "SET_ME"
      - key: VITE_GOOGLE_CLIENT_ID
        value: "SET_ME"
